class constant:
    QUITING = 99
    USER_CONNECTING = 0
    HOMESCREEN_CONNECTS = 1
    HOMESCREEN_QUITING = 2
    NEW_GAMESERVER = 3
    GAMESERVER_UPDATE = 4
    SERVER_QUIT = 5
    CHECK_LIVE = 6
